.TH POCKETSPHINX_SWB 1 "2007-08-27"
.SH NAME
pocketsphinx_swb \- Run PocketSphinx with the swb5k language model
.SH SYNOPSIS
.B pocketsphinx_swb
.SH DESCRIPTION
.PP
This is a small script to run PocketSphinx in continuous listening
mode using the swb5k language model and the wsj1 acoustic model.  This
language model is trained froma 5000-word subset of the Switchboard
conversational telephone speech transcriptions.  It is a "toy"
language model and is not suitable for real applications.
.SH AUTHOR
Written by David Huggins-Daines <dhuggins@cs.cmu.edu>.
.SH COPYRIGHT
Copyright \(co 2006 Carnegie Mellon University.  See the file
\fICOPYING\fR included with this package for more information.
.br
.SH "SEE ALSO"
.BR pocketsphinx_continuous (1).
.br
