.TH POCKETSPHINX_WSJ 1 "2008-07-07"
.SH NAME
pocketsphinx_wsj \- Run continuous word recognition with PocketSphinx
.SH SYNOPSIS
.B pocketsphinx_wsj
.SH DESCRIPTION
.PP
This is a small script to run PocketSphinx in continuous listening
mode using the WSJ acoustic and language models.  These models are
trained for 8kHz English microphone speech with a vocabulary of 5000
words.
.SH AUTHOR
Written by David Huggins-Daines <dhuggins@cs.cmu.edu>.
.SH COPYRIGHT
Copyright \(co 2008 Carnegie Mellon University.  See the file
\fICOPYING\fR included with this package for more information.
.br
.SH "SEE ALSO"
.BR pocketsphinx_continuous (1).
.br
