.TH SPHINX_CEPVIEW 1 "2007-08-27"
.SH NAME
sphinx_cepview \- View acoustic feature files
.SH SYNOPSIS
.B sphinx_cepview
[\fI options \fR]...
.SH DESCRIPTION
.PP
This program reads acoustic feature files in Sphinx format and
displays their contents as text for inspection.
.TP
.B \-b
The beginning frame 0-based.
.TP
.B \-d
Number of displayed coefficients.
.TP
.B \-describe
Whether description will be shown.
.TP
.B \-e
The ending frame.
.TP
.B \-f
feature file.
.TP
.B \-header
Whether header is shown.
.TP
.B \-i
Number of coefficients in the feature vector.
.TP
.B \-logfn
file (default stdout/stderr)
.SH AUTHOR
Written by numerous people at CMU from 1994 onwards.  This manual page
by David Huggins-Daines <dhuggins@cs.cmu.edu>
.SH COPYRIGHT
Copyright \(co 1994-2007 Carnegie Mellon University.  See the file
\fICOPYING\fR included with this package for more information.
.br
